### PR TITLE
Add stack navigation in auth screens

### PR DESCRIPTION
**Pull request by psakurai**

### CODE REVIEW

**Comment by psakurai** [comment]
The navigation for auth screen is now working fine, but the code still ain't split to different files yet.

**Comment by mangkoran** [comment]
Alright. Maybe I just let this PR opened while you splitting the code. LMK if its ready to be merged.

**Comment by psakurai** [comment]
I think its better to merge the code first, then split. So everyone can get the hang on how to connect with the back-end code. Of course after conflicts are resolved.

**Comment by psakurai** [comment]
Splitting the code might take longer than expected.

**Pull request merged**
