### PR TITLE
update profile screen

### PR DESCRIPTION
**Pull request by mangkoran**
- build: add react-native-paper
- feat: wrap root component with react-native-paper provider
- feat: profile screen menu

### CODE REVIEW

**Review by mangkoran — COMMENTED** [review]
@psakurai Could you please use `TextInput` and `Pressable` instead of `Text` and `TouchableOpacity`?

**Comment by psakurai** [comment]
> @psakurai Could you please use `TextInput` and `Pressable` instead of `Text` and `TouchableOpacity`?

Already change to pressable at 4d08b9e [](https://github.com/t-analog/crowdfinder-client/pull/73/commits/4d08b9eea7022e0d7044ac6dbdc0eb1d2d5fd633)

**Pull request merged**
